-- resolveit-db.sql
DROP DATABASE IF EXISTS resolveit;
CREATE DATABASE resolveit CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE resolveit;

-- Roles
CREATE TABLE roles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
);

-- Users
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(150),
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(150),
  is_active TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- user_roles junction
CREATE TABLE user_roles (
  user_id INT NOT NULL,
  role_id INT NOT NULL,
  PRIMARY KEY(user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- Complaint status master
CREATE TABLE complaint_status (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  display VARCHAR(100) NOT NULL
);

-- Complaints
CREATE TABLE complaints (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  category VARCHAR(100),
  priority ENUM('LOW','MEDIUM','HIGH') DEFAULT 'LOW',
  is_anonymous TINYINT(1) DEFAULT 0,
  user_id INT NULL,
  status_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (status_id) REFERENCES complaint_status(id)
);

-- Attachments
CREATE TABLE attachments (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  complaint_id BIGINT NOT NULL,
  filename VARCHAR(255),
  file_path VARCHAR(500),
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (complaint_id) REFERENCES complaints(id) ON DELETE CASCADE
);

-- Comments / Timeline entries (public replies or admin notes)
CREATE TABLE comments (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  complaint_id BIGINT NOT NULL,
  author_id INT NULL,
  message TEXT,
  is_private TINYINT(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (complaint_id) REFERENCES complaints(id) ON DELETE CASCADE,
  FOREIGN KEY (author_id) REFERENCES users(id)
);

-- Escalation table
CREATE TABLE escalations (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  complaint_id BIGINT NOT NULL,
  escalated_to_role INT NOT NULL,
  reason TEXT,
  escalated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  resolved TINYINT(1) DEFAULT 0,
  FOREIGN KEY (complaint_id) REFERENCES complaints(id),
  FOREIGN KEY (escalated_to_role) REFERENCES roles(id)
);

-- initial data
INSERT INTO roles (name) VALUES ('ROLE_USER'), ('ROLE_ADMIN'), ('ROLE_SUPERVISOR');

INSERT INTO complaint_status (code, display) VALUES
('NEW','New'),
('UNDER_REVIEW','Under Review'),
('IN_PROGRESS','In Progress'),
('RESOLVED','Resolved'),
('ESCALATED','Escalated');

-- Sample users with bcrypt hashes for "Password123" (replace with your own in production).
-- These hashes are generated by BCrypt and expected to match "Password123".
INSERT INTO users (username, email, password_hash, full_name, is_active) VALUES
('alice','alice@example.com','$2a$10$2yY9lVhHqG8c0J8jYzZD7e1m4y8kYcJg1AGQn1a8XKcYQGgkWzD9a','Alice Kumar',1),
('bob','bob@example.com','$2a$10$2yY9lVhHqG8c0J8jYzZD7e1m4y8kYcJg1AGQn1a8XKcYQGgkWzD9a','Bob Sharma',1),
('admin','admin@example.com','$2a$10$2yY9lVhHqG8c0J8jYzZD7e1m4y8kYcJg1AGQn1a8XKcYQGgkWzD9a','Admin User',1);

-- link roles (1->alice user, 2->bob user, 3->admin user)
INSERT INTO user_roles (user_id, role_id) VALUES
(1,1),(2,1),(3,2);

-- sample complaints
INSERT INTO complaints (title, description, category, priority, is_anonymous, user_id, status_id)
VALUES
('Broken light in corridor', 'The corridor light at Block B floor 2 has been broken for 10 days.', 'Infrastructure', 'HIGH', 0, 1, 1),
('Canteen hygiene', 'Found unclean utensils twice this week.', 'Services', 'MEDIUM', 1, NULL, 1);

-- sample comments
INSERT INTO comments (complaint_id, author_id, message, is_private)
VALUES
(1,3,'Assigned to maintenance team','1'),
(1,3,'Maintenance will visit on Monday','0');
